version: '3.8'

services:

  orders-db:
    image: postgres:15
    container_name: orders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OrdersMicroservice
    ports:
      - 5434:5434
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    networks:
      - kafka
    
  payments-db:
    image: postgres:15
    container_name: payments-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PaymentsMicroservice
    ports:
      - 5435:54345
    volumes:
      - payments-db-data:/var/lib/postgresql/data
    networks:
      - kafka


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LOG_RETENTION_MS=60000
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - kafka


  payment-http:
    image: payment-http
    build:
      context: ./Payment
      dockerfile: Dockerfile
    ports:
      - 8081:81 
    depends_on:
      - kafka
    networks:
      - kafka

  
  orders-http:
    image: orders-http 
    build:
      context: ./Orders
      dockerfile: Dockerfile 
    ports:
      - 8080:80 
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:

volumes:
  orders-db-data:
  payments-db-data: